### ISSUE TITLE
Xcode 10.3 swift compiler issue

### ISSUE THREAD

**Issue by ir2pid** [heidelpay/heidelpay-iOS#1]
I'm adding the framework manually and get this error in Xcode 10.3
Seems you need to build the binary with a newer swift compiler for it to work on the Xcode 10.3

`xx/Heidelpay.swift:5:8: Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.0.1 compiler:xx/Plugins/cordova-plugin-heidelpay/HeidelpaySDK.framework/Modules/HeidelpaySDK.swiftmodule/x86_64.swiftmodule`

Reference:
[Reddit error discussion]
(https://www.reddit.com/r/swift/comments/ba08ea/module_compiled_with_swift_421_cannot_be_imported/)
[Stackoverflow thread](https://stackoverflow.com/questions/55352985/module-compiled-with-swift-4-2-1-cannot-be-imported-by-the-swift-5-0-compiler)

**Comment by martinkahr** [comment]
Thanks for the information. We currently wait for the final version of Xcode 11 and will then provide another binary. Unfortunately different versions of Xcode ship with different versions of the Swift compiler and we can't upload multiple binaries on GitHub. We recommend to use the integration with CocoaPods or Carthage which will recompile the framework with your specific toolset.
